In [5]:
import pandas as pd
import requests

In [2]:
# Ścieżka do pliku CSV
csv_path = "revenues_per_day.csv"

# Wczytanie danych
df = pd.read_csv(csv_path)

In [15]:
df.count()

id             337818
date           337818
title          337818
revenue        337818
theaters       337657
distributor    337593
dtype: int64

In [6]:
df.head(400)

,id,date,title,revenue,theaters,distributor
0,8b19ad43-3a7e-b14b-49e9-1f7a0eb1568e,2004-09-20,Sky Captain and the World of Tomorrow,925482,3170.0,Paramount Pictures
1,481fc700-fcdd-1919-c53c-09fcd423a596,2004-09-20,Resident Evil: Apocalypse,643680,3284.0,Screen Gems
2,06719cc2-c05e-8c0b-56b6-b8b13e056509,2004-09-20,Mr 3000,425375,2736.0,Walt Disney Studios Motion Pictures
3,3be8e4a8-2716-00be-80be-eb342ba3cbe7,2004-09-20,Wimbledon,416970,2034.0,Universal Pictures
4,c5f26b59-6a64-ae8e-8f58-7cefb09eadfe,2004-09-20,Cellular,412000,2749.0,New Line Cinema
...,...,...,...,...,...,...
395,fe157987-17fc-56df-0184-65670b3cd264,2009-06-25,Fast & Furious,16560,184.0,Universal Pictures
396,71eec143-6408-e148-2fe2-6e30bbd59afc,2009-06-25,Knowing,11482,115.0,Summit Entertainment
397,2bae8d43-45c9-b6ca-affe-8780f4ff193d,2009-06-25,Sunshine Cleaning,8967,134.0,Overture Films
398,311a363c-ce00-8e3b-7ee0-da77f4896683,2009-06-25,Next Day Air,8692,133.0,Summit Entertainment
399,a0e0f2f5-e8f6-d0af-0659-c8f2e6f0c302,2009-06-25,Tetro,5668,8.0,American Zoetrope

In [10]:
OMDB_API_KEY="e4cc9277"
url = f"http://www.omdbapi.com/?apikey={OMDB_API_KEY}"

In [16]:
# title = "Sky Captain and the World of Tomorrow"
title = "Wimbledon"

In [17]:
url_title = f"{url}&t={title}"
response = requests.get(url_title)
data_2 = response.json()

In [13]:
data

{'Title': 'Sky Captain and the World of Tomorrow',
 'Year': '2004',
 'Rated': 'PG',
 'Released': '17 Sep 2004',
 'Runtime': '106 min',
 'Genre': 'Action, Adventure, Mystery',
 'Director': 'Kerry Conran',
 'Writer': 'Kerry Conran',
 'Actors': 'Gwyneth Paltrow, Jude Law, Angelina Jolie',
 'Plot': 'After New York City receives a series of attacks from giant flying robots, a reporter teams up with a pilot in search of their origin, as well as the reason for the disappearances of famous scientists around the world.',
 'Language': 'English, Tibetan, German',
 'Country': 'United Kingdom, Italy, United States',
 'Awards': '8 wins & 19 nominations total',
 'Poster': 'https://m.media-amazon.com/images/M/MV5BMTM0NDQzMDA1NF5BMl5BanBnXkFtZTcwNTU3ODAzMw@@._V1_SX300.jpg',
 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.1/10'},
  {'Source': 'Rotten Tomatoes', 'Value': '71%'},
  {'Source': 'Metacritic', 'Value': '64/100'}],
 'Metascore': '64',
 'imdbRating': '6.1',
 'imdbVotes': '88,686',
 'imdbID': 'tt0346156',
 'Type': 'movie',
 'DVD': 'N/A',
 'BoxOffice': '$37,762,677',
 'Production': 'N/A',
 'Website': 'N/A',
 'Response': 'True'}

In [18]:
data_2

{'Title': 'Wimbledon',
 'Year': '2004',
 'Rated': 'PG-13',
 'Released': '17 Sep 2004',
 'Runtime': '98 min',
 'Genre': 'Comedy, Romance, Sport',
 'Director': 'Richard Loncraine',
 'Writer': 'Adam Brooks, Jennifer Flackett, Mark Levin',
 'Actors': 'Kirsten Dunst, Paul Bettany, Jon Favreau',
 'Plot': "A pro tennis player has lost his ambition and has fallen in rank to 119. Fortunately for him, he meets a young player on the women's circuit who helps him recapture his focus for Wimbledon.",
 'Language': 'English, Italian',
 'Country': 'United Kingdom, France, United States',
 'Awards': '1 nomination total',
 'Poster': 'https://m.media-amazon.com/images/M/MV5BOTg1ZmFkNDYtOTA1ZS00NjMwLWEwZGUtNDc0NDFhMzEzNmExXkEyXkFqcGc@._V1_SX300.jpg',
 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.3/10'},
  {'Source': 'Rotten Tomatoes', 'Value': '60%'},
  {'Source': 'Metacritic', 'Value': '59/100'}],
 'Metascore': '59',
 'imdbRating': '6.3',
 'imdbVotes': '68,364',
 'imdbID': 'tt0360201',
 'Type': 'movie',
 'DVD': 'N/A',
 'BoxOffice': '$17,001,133',
 'Production': 'N/A',
 'Website': 'N/A',
 'Response': 'True'}

In [20]:
URL = f"http://www.omdbapi.com/?apikey={OMDB_API_KEY}"
def fetch_movie_data(title):
    url_title = f"{URL}&t={title}"
    response = requests.get(url_title)
    data = response.json()
    
    if data.get("Response") == "False":
        print("Brak danych")

    return data

In [23]:
unique_titles = df['title'].unique()
unique_titles_3 = unique_titles[0:3]
unique_titles_3

array(['Sky Captain and the World of Tomorrow',
       'Resident Evil: Apocalypse', 'Mr 3000'], dtype=object)

In [24]:
movie_data = []

for title in unique_titles_3:
    data = fetch_movie_data(title)
    movie_data.append(data)

In [25]:
movie_data

[{'Title': 'Sky Captain and the World of Tomorrow',
  'Year': '2004',
  'Rated': 'PG',
  'Released': '17 Sep 2004',
  'Runtime': '106 min',
  'Genre': 'Action, Adventure, Mystery',
  'Director': 'Kerry Conran',
  'Writer': 'Kerry Conran',
  'Actors': 'Gwyneth Paltrow, Jude Law, Angelina Jolie',
  'Plot': 'After New York City receives a series of attacks from giant flying robots, a reporter teams up with a pilot in search of their origin, as well as the reason for the disappearances of famous scientists around the world.',
  'Language': 'English, Tibetan, German',
  'Country': 'United Kingdom, Italy, United States',
  'Awards': '8 wins & 19 nominations total',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BMTM0NDQzMDA1NF5BMl5BanBnXkFtZTcwNTU3ODAzMw@@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.1/10'},
   {'Source': 'Rotten Tomatoes', 'Value': '71%'},
   {'Source': 'Metacritic', 'Value': '64/100'}],
  'Metascore': '64',
  'imdbRating': '6.1',
  'imdbVotes': '88,686',
  'imdbID': 'tt0346156',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': '$37,762,677',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True'},
 {'Title': 'Resident Evil: Apocalypse',
  'Year': '2004',
  'Rated': 'R',
  'Released': '10 Sep 2004',
  'Runtime': '94 min',
  'Genre': 'Action, Horror, Sci-Fi',
  'Director': 'Alexander Witt',
  'Writer': 'Paul W.S. Anderson',
  'Actors': 'Milla Jovovich, Sienna Guillory, Eric Mabius',
  'Plot': 'Alice wakes up in the Raccoon City hospital after the area has been overrun by zombies, and must now make it out of the city before a nuclear bomb is dropped.',
  'Language': 'English',
  'Country': 'Germany, United Kingdom, France, Canada, United States',
  'Awards': '6 wins & 3 nominations total',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BMTc1NTUxMzk0Nl5BMl5BanBnXkFtZTcwNDQ1MDIzMw@@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.1/10'},
   {'Source': 'Rotten Tomatoes', 'Value': '18%'},
   {'Source': 'Metacritic', 'Value': '36/100'}],
  'Metascore': '36',
  'imdbRating': '6.1',
  'imdbVotes': '216,972',
  'imdbID': 'tt0318627',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': '$51,201,453',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True'},
 {'Title': 'Mr. 3000',
  'Year': '2004',
  'Rated': 'PG-13',
  'Released': '17 Sep 2004',
  'Runtime': '104 min',
  'Genre': 'Comedy, Drama, Romance',
  'Director': 'Charles Stone III',
  'Writer': 'Eric Champnella, Keith Mitchell, Howard Michael Gould',
  'Actors': 'Bernie Mac, Angela Bassett, Michael Rispoli',
  'Plot': "Aging baseball star who goes by the nickname, Mr. 3000, finds out many years after retirement that he didn't quite reach 3,000 hits. Now at age 47 he's back to try and reach that goal.",
  'Language': 'English',
  'Country': 'United States',
  'Awards': '1 win & 5 nominations',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BMTg5NTk2MTQ0NV5BMl5BanBnXkFtZTcwNjMyNTUyMQ@@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '5.6/10'},
   {'Source': 'Rotten Tomatoes', 'Value': '54%'},
   {'Source': 'Metacritic', 'Value': '57/100'}],
  'Metascore': '57',
  'imdbRating': '5.6',
  'imdbVotes': '15,332',
  'imdbID': 'tt0339412',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': '$21,811,187',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True'}]

In [26]:
movie_df = pd.DataFrame(movie_data)

In [27]:
movie_df

,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,...,Metascore,imdbRating,imdbVotes,imdbID,Type,DVD,BoxOffice,Production,Website,Response
0,Sky Captain and the World of Tomorrow,2004,PG,17 Sep 2004,106 min,"Action, Adventure, Mystery",Kerry Conran,Kerry Conran,"Gwyneth Paltrow, Jude Law, Angelina Jolie",After New York City receives a series of attac...,...,64,6.1,"88,686",tt0346156,movie,N/A,"$37,762,677",N/A,N/A,True
1,Resident Evil: Apocalypse,2004,R,10 Sep 2004,94 min,"Action, Horror, Sci-Fi",Alexander Witt,Paul W.S. Anderson,"Milla Jovovich, Sienna Guillory, Eric Mabius",Alice wakes up in the Raccoon City hospital af...,...,36,6.1,"216,972",tt0318627,movie,N/A,"$51,201,453",N/A,N/A,True
2,Mr. 3000,2004,PG-13,17 Sep 2004,104 min,"Comedy, Drama, Romance",Charles Stone III,"Eric Champnella, Keith Mitchell, Howard Michae...","Bernie Mac, Angela Bassett, Michael Rispoli","Aging baseball star who goes by the nickname, ...",...,57,5.6,"15,332",tt0339412,movie,N/A,"$21,811,187",N/A,N/A,True

In [28]:
movie_df["Ratings"]

0    [{'Source': 'Internet Movie Database', 'Value'...
1    [{'Source': 'Internet Movie Database', 'Value'...
2    [{'Source': 'Internet Movie Database', 'Value'...
Name: Ratings, dtype: object

In [29]:
df

,id,date,title,revenue,theaters,distributor
0,8b19ad43-3a7e-b14b-49e9-1f7a0eb1568e,2004-09-20,Sky Captain and the World of Tomorrow,925482,3170.0,Paramount Pictures
1,481fc700-fcdd-1919-c53c-09fcd423a596,2004-09-20,Resident Evil: Apocalypse,643680,3284.0,Screen Gems
2,06719cc2-c05e-8c0b-56b6-b8b13e056509,2004-09-20,Mr 3000,425375,2736.0,Walt Disney Studios Motion Pictures
3,3be8e4a8-2716-00be-80be-eb342ba3cbe7,2004-09-20,Wimbledon,416970,2034.0,Universal Pictures
4,c5f26b59-6a64-ae8e-8f58-7cefb09eadfe,2004-09-20,Cellular,412000,2749.0,New Line Cinema
...,...,...,...,...,...,...
337813,4fe930ae-1b51-1b69-d6ba-f1b087db791c,2023-03-06,The Fabelmans,7555,591.0,Universal Pictures
337814,a4f1ad5e-11c0-5b07-9fe1-7adcade7da8c,2023-03-06,Selfiee,4800,308.0,-
337815,225197d3-d1e9-aca0-68b6-ba9fe61b2dc6,2023-03-06,The Banshees of Inisherin,3158,270.0,Searchlight Pictures
337816,1110f122-765c-43a9-bccf-c26311a863a5,2023-03-06,Violent Night,530,49.0,Universal Pictures
337817,831f1fa6-9699-32a3-fe0f-d0b47d8ba80f,2023-03-06,Black Panther: Wakanda Forever,529,40.0,Walt Disney Studios Motion Pictures

In [31]:
df.columns

Index(['id', 'date', 'title', 'revenue', 'theaters', 'distributor'], dtype='object')

In [36]:
movie_df.dtypes

Title         object
Year          object
Rated         object
Released      object
Runtime       object
Genre         object
Director      object
Writer        object
Actors        object
Plot          object
Language      object
Country       object
Awards        object
Poster        object
Ratings       object
Metascore     object
imdbRating    object
imdbVotes     object
imdbID        object
Type          object
DVD           object
BoxOffice     object
Production    object
Website       object
Response      object
dtype: object

In [37]:
movie_df['Genre']

0    Action, Adventure, Mystery
1        Action, Horror, Sci-Fi
2        Comedy, Drama, Romance
Name: Genre, dtype: object

In [32]:
movie_df.columns

Index(['Title', 'Year', 'Rated', 'Released', 'Runtime', 'Genre', 'Director',
       'Writer', 'Actors', 'Plot', 'Language', 'Country', 'Awards', 'Poster',
       'Ratings', 'Metascore', 'imdbRating', 'imdbVotes', 'imdbID', 'Type',
       'DVD', 'BoxOffice', 'Production', 'Website', 'Response'],
      dtype='object')

In [ ]:
'Title', 
'Year', 
'Rated', 
'Released', 
'Runtime', 
'Genre', 
'Director',
'Writer', 
'Actors', 
'Plot', 
'Language', 
'Country', 
'Awards', 
'Poster',
'Ratings', 
'Metascore', 
'imdbRating', 
'imdbVotes', 
'imdbID', 
'Type',
'DVD', 
'BoxOffice', 
'Production', 
'Website',
'Response'